package com.example.springbootdemo.common.db.dao.quartz.qrtztriggers.mapper;

import com.example.springbootdemo.common.db.dao.quartz.qrtztriggers.model.QrtzTriggers;
import com.example.springbootdemo.common.db.dao.quartz.qrtztriggers.model.QrtzTriggersExample;
import com.example.springbootdemo.common.db.dao.quartz.qrtztriggers.model.QrtzTriggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    int countByExample(QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    int deleteByExample(QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    int deleteByPrimaryKey(QrtzTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    int insert(QrtzTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    int insertSelective(QrtzTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    List<QrtzTriggers> selectByExampleWithBLOBs(QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    List<QrtzTriggers> selectByExample(QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    QrtzTriggers selectByPrimaryKey(QrtzTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") QrtzTriggers record, @Param("example") QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") QrtzTriggers record, @Param("example") QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    int updateByExample(@Param("record") QrtzTriggers record, @Param("example") QrtzTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    int updateByPrimaryKeySelective(QrtzTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(QrtzTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:51 CST 2020
     */
    int updateByPrimaryKey(QrtzTriggers record);
}