package com.example.springbootdemo.common.db.dao.dbsavefront.mapper;

import com.example.springbootdemo.common.db.dao.dbsavefront.model.DbSaveFront;
import com.example.springbootdemo.common.db.dao.dbsavefront.model.DbSaveFrontExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DbSaveFrontMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    int countByExample(DbSaveFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    int deleteByExample(DbSaveFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    int insert(DbSaveFront record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    int insertSelective(DbSaveFront record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    List<DbSaveFront> selectByExample(DbSaveFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    DbSaveFront selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") DbSaveFront record, @Param("example") DbSaveFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    int updateByExample(@Param("record") DbSaveFront record, @Param("example") DbSaveFrontExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    int updateByPrimaryKeySelective(DbSaveFront record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    int updateByPrimaryKey(DbSaveFront record);
}