package com.example.springbootdemo.common.db.dao.quartz.qrtzjobdetails.model;

public class QrtzJobDetailsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.SCHED_NAME
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.JOB_NAME
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_JOB_DETAILS.JOB_GROUP
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    private String jobGroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.SCHED_NAME
     *
     * @return the value of QRTZ_JOB_DETAILS.SCHED_NAME
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.SCHED_NAME
     *
     * @param schedName the value for QRTZ_JOB_DETAILS.SCHED_NAME
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.JOB_NAME
     *
     * @return the value of QRTZ_JOB_DETAILS.JOB_NAME
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.JOB_NAME
     *
     * @param jobName the value for QRTZ_JOB_DETAILS.JOB_NAME
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_JOB_DETAILS.JOB_GROUP
     *
     * @return the value of QRTZ_JOB_DETAILS.JOB_GROUP
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_JOB_DETAILS.JOB_GROUP
     *
     * @param jobGroup the value for QRTZ_JOB_DETAILS.JOB_GROUP
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup == null ? null : jobGroup.trim();
    }
}