package com.example.springbootdemo.common.db.dao.quartz.qrtzblobtriggers.mapper;

import com.example.springbootdemo.common.db.dao.quartz.qrtzblobtriggers.model.QrtzBlobTriggers;
import com.example.springbootdemo.common.db.dao.quartz.qrtzblobtriggers.model.QrtzBlobTriggersExample;
import com.example.springbootdemo.common.db.dao.quartz.qrtzblobtriggers.model.QrtzBlobTriggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzBlobTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    int countByExample(QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    int deleteByExample(QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    int deleteByPrimaryKey(QrtzBlobTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    int insert(QrtzBlobTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    int insertSelective(QrtzBlobTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    List<QrtzBlobTriggers> selectByExampleWithBLOBs(QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    List<QrtzBlobTriggers> selectByExample(QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    QrtzBlobTriggers selectByPrimaryKey(QrtzBlobTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    int updateByExampleSelective(@Param("record") QrtzBlobTriggers record, @Param("example") QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") QrtzBlobTriggers record, @Param("example") QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    int updateByExample(@Param("record") QrtzBlobTriggers record, @Param("example") QrtzBlobTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    int updateByPrimaryKeySelective(QrtzBlobTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_BLOB_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(QrtzBlobTriggers record);
}