package com.example.springbootdemo.common.db.dao.testtable.model;

import java.util.Date;

public class TestTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.test_id
     *
     * @mbggenerated Sun Mar 08 20:46:21 CST 2020
     */
    private Long testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.test_name
     *
     * @mbggenerated Sun Mar 08 20:46:21 CST 2020
     */
    private String testName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.gmt_create
     *
     * @mbggenerated Sun Mar 08 20:46:21 CST 2020
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table.gmt_update
     *
     * @mbggenerated Sun Mar 08 20:46:21 CST 2020
     */
    private Date gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.test_id
     *
     * @return the value of test_table.test_id
     *
     * @mbggenerated Sun Mar 08 20:46:21 CST 2020
     */
    public Long getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.test_id
     *
     * @param testId the value for test_table.test_id
     *
     * @mbggenerated Sun Mar 08 20:46:21 CST 2020
     */
    public void setTestId(Long testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.test_name
     *
     * @return the value of test_table.test_name
     *
     * @mbggenerated Sun Mar 08 20:46:21 CST 2020
     */
    public String getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.test_name
     *
     * @param testName the value for test_table.test_name
     *
     * @mbggenerated Sun Mar 08 20:46:21 CST 2020
     */
    public void setTestName(String testName) {
        this.testName = testName == null ? null : testName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.gmt_create
     *
     * @return the value of test_table.gmt_create
     *
     * @mbggenerated Sun Mar 08 20:46:21 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.gmt_create
     *
     * @param gmtCreate the value for test_table.gmt_create
     *
     * @mbggenerated Sun Mar 08 20:46:21 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table.gmt_update
     *
     * @return the value of test_table.gmt_update
     *
     * @mbggenerated Sun Mar 08 20:46:21 CST 2020
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table.gmt_update
     *
     * @param gmtUpdate the value for test_table.gmt_update
     *
     * @mbggenerated Sun Mar 08 20:46:21 CST 2020
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}