package com.example.springbootdemo.common.db.dao.adminoperatelog.model;

import java.util.Date;

public class AdminOperateLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_operate_log.id
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_operate_log.operator
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_operate_log.gmt_create
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_operate_log.content
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_operate_log.id
     *
     * @return the value of admin_operate_log.id
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_operate_log.id
     *
     * @param id the value for admin_operate_log.id
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_operate_log.operator
     *
     * @return the value of admin_operate_log.operator
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_operate_log.operator
     *
     * @param operator the value for admin_operate_log.operator
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_operate_log.gmt_create
     *
     * @return the value of admin_operate_log.gmt_create
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_operate_log.gmt_create
     *
     * @param gmtCreate the value for admin_operate_log.gmt_create
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_operate_log.content
     *
     * @return the value of admin_operate_log.content
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_operate_log.content
     *
     * @param content the value for admin_operate_log.content
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}