package com.example.springbootdemo.common.db.dao.quartz.qrtzcrontriggers.mapper;

import com.example.springbootdemo.common.db.dao.quartz.qrtzcrontriggers.model.QrtzCronTriggers;
import com.example.springbootdemo.common.db.dao.quartz.qrtzcrontriggers.model.QrtzCronTriggersExample;
import com.example.springbootdemo.common.db.dao.quartz.qrtzcrontriggers.model.QrtzCronTriggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzCronTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:55 CST 2020
     */
    int countByExample(QrtzCronTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:55 CST 2020
     */
    int deleteByExample(QrtzCronTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:55 CST 2020
     */
    int deleteByPrimaryKey(QrtzCronTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:55 CST 2020
     */
    int insert(QrtzCronTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:55 CST 2020
     */
    int insertSelective(QrtzCronTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:55 CST 2020
     */
    List<QrtzCronTriggers> selectByExample(QrtzCronTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:55 CST 2020
     */
    QrtzCronTriggers selectByPrimaryKey(QrtzCronTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") QrtzCronTriggers record, @Param("example") QrtzCronTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:55 CST 2020
     */
    int updateByExample(@Param("record") QrtzCronTriggers record, @Param("example") QrtzCronTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:55 CST 2020
     */
    int updateByPrimaryKeySelective(QrtzCronTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CRON_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:55 CST 2020
     */
    int updateByPrimaryKey(QrtzCronTriggers record);
}