package com.example.springbootdemo.common.db.dao.quartz.qrtzschedulerstate.model;

public class QrtzSchedulerState extends QrtzSchedulerStateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @mbggenerated Thu Oct 08 21:39:14 CST 2020
     */
    private Long lastCheckinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @mbggenerated Thu Oct 08 21:39:14 CST 2020
     */
    private Long checkinInterval;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @return the value of QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @mbggenerated Thu Oct 08 21:39:14 CST 2020
     */
    public Long getLastCheckinTime() {
        return lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @param lastCheckinTime the value for QRTZ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @mbggenerated Thu Oct 08 21:39:14 CST 2020
     */
    public void setLastCheckinTime(Long lastCheckinTime) {
        this.lastCheckinTime = lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @return the value of QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @mbggenerated Thu Oct 08 21:39:14 CST 2020
     */
    public Long getCheckinInterval() {
        return checkinInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @param checkinInterval the value for QRTZ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @mbggenerated Thu Oct 08 21:39:14 CST 2020
     */
    public void setCheckinInterval(Long checkinInterval) {
        this.checkinInterval = checkinInterval;
    }
}