package com.example.springbootdemo.common.db.dao.quartz.qrtzcalendars.mapper;

import com.example.springbootdemo.common.db.dao.quartz.qrtzcalendars.model.QrtzCalendars;
import com.example.springbootdemo.common.db.dao.quartz.qrtzcalendars.model.QrtzCalendarsExample;
import com.example.springbootdemo.common.db.dao.quartz.qrtzcalendars.model.QrtzCalendarsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzCalendarsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Thu Oct 08 21:43:57 CST 2020
     */
    int countByExample(QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Thu Oct 08 21:43:57 CST 2020
     */
    int deleteByExample(QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Thu Oct 08 21:43:57 CST 2020
     */
    int deleteByPrimaryKey(QrtzCalendarsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Thu Oct 08 21:43:57 CST 2020
     */
    int insert(QrtzCalendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Thu Oct 08 21:43:57 CST 2020
     */
    int insertSelective(QrtzCalendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Thu Oct 08 21:43:57 CST 2020
     */
    List<QrtzCalendars> selectByExampleWithBLOBs(QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Thu Oct 08 21:43:57 CST 2020
     */
    List<QrtzCalendars> selectByExample(QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Thu Oct 08 21:43:57 CST 2020
     */
    QrtzCalendars selectByPrimaryKey(QrtzCalendarsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Thu Oct 08 21:43:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") QrtzCalendars record, @Param("example") QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Thu Oct 08 21:43:57 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") QrtzCalendars record, @Param("example") QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Thu Oct 08 21:43:57 CST 2020
     */
    int updateByExample(@Param("record") QrtzCalendars record, @Param("example") QrtzCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Thu Oct 08 21:43:57 CST 2020
     */
    int updateByPrimaryKeySelective(QrtzCalendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_CALENDARS
     *
     * @mbggenerated Thu Oct 08 21:43:57 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(QrtzCalendars record);
}