package org.example.db.dao.bizlock.model;

import java.util.Date;

public class BizLock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lock.id
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lock.biz_id
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    private String bizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lock.biz_type
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    private String bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lock.lock_type
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    private String lockType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lock.lock_time
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    private Date lockTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_lock.version
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lock.id
     *
     * @return the value of biz_lock.id
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lock.id
     *
     * @param id the value for biz_lock.id
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lock.biz_id
     *
     * @return the value of biz_lock.biz_id
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    public String getBizId() {
        return bizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lock.biz_id
     *
     * @param bizId the value for biz_lock.biz_id
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    public void setBizId(String bizId) {
        this.bizId = bizId == null ? null : bizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lock.biz_type
     *
     * @return the value of biz_lock.biz_type
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lock.biz_type
     *
     * @param bizType the value for biz_lock.biz_type
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lock.lock_type
     *
     * @return the value of biz_lock.lock_type
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    public String getLockType() {
        return lockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lock.lock_type
     *
     * @param lockType the value for biz_lock.lock_type
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    public void setLockType(String lockType) {
        this.lockType = lockType == null ? null : lockType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lock.lock_time
     *
     * @return the value of biz_lock.lock_time
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    public Date getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lock.lock_time
     *
     * @param lockTime the value for biz_lock.lock_time
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_lock.version
     *
     * @return the value of biz_lock.version
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_lock.version
     *
     * @param version the value for biz_lock.version
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}