package com.example.springbootdemo.common.db.dao.odps.model;

import java.util.Date;

public class Odps {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column odps.id
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column odps.tableName
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    private String tablename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column odps.userName
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column odps.gmt_create
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column odps.gme_update
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    private Date gmeUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column odps.is_delete
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column odps.description
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column odps.id
     *
     * @return the value of odps.id
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column odps.id
     *
     * @param id the value for odps.id
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column odps.tableName
     *
     * @return the value of odps.tableName
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public String getTablename() {
        return tablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column odps.tableName
     *
     * @param tablename the value for odps.tableName
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public void setTablename(String tablename) {
        this.tablename = tablename == null ? null : tablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column odps.userName
     *
     * @return the value of odps.userName
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column odps.userName
     *
     * @param username the value for odps.userName
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column odps.gmt_create
     *
     * @return the value of odps.gmt_create
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column odps.gmt_create
     *
     * @param gmtCreate the value for odps.gmt_create
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column odps.gme_update
     *
     * @return the value of odps.gme_update
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public Date getGmeUpdate() {
        return gmeUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column odps.gme_update
     *
     * @param gmeUpdate the value for odps.gme_update
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public void setGmeUpdate(Date gmeUpdate) {
        this.gmeUpdate = gmeUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column odps.is_delete
     *
     * @return the value of odps.is_delete
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column odps.is_delete
     *
     * @param isDelete the value for odps.is_delete
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column odps.description
     *
     * @return the value of odps.description
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column odps.description
     *
     * @param description the value for odps.description
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}