package com.example.springbootdemo.common.db.dao.adminoperatelog.mapper;

import com.example.springbootdemo.common.db.dao.adminoperatelog.model.AdminOperateLog;
import com.example.springbootdemo.common.db.dao.adminoperatelog.model.AdminOperateLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminOperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    int countByExample(AdminOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    int deleteByExample(AdminOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    int insert(AdminOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    int insertSelective(AdminOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    List<AdminOperateLog> selectByExampleWithBLOBs(AdminOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    List<AdminOperateLog> selectByExample(AdminOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    AdminOperateLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    int updateByExampleSelective(@Param("record") AdminOperateLog record, @Param("example") AdminOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") AdminOperateLog record, @Param("example") AdminOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    int updateByExample(@Param("record") AdminOperateLog record, @Param("example") AdminOperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    int updateByPrimaryKeySelective(AdminOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(AdminOperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operate_log
     *
     * @mbggenerated Fri Jan 22 23:35:21 CST 2021
     */
    int updateByPrimaryKey(AdminOperateLog record);
}