package com.example.springbootdemo.common.db.dao.userinfos.model;

import java.util.Date;

public class Userinfos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfos.id
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfos.username
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfos.nickname
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfos.age
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfos.email
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfos.gmt_create
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfos.gmt_update
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    private Date gmtUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfos.is_delete
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfos.id
     *
     * @return the value of userinfos.id
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfos.id
     *
     * @param id the value for userinfos.id
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfos.username
     *
     * @return the value of userinfos.username
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfos.username
     *
     * @param username the value for userinfos.username
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfos.nickname
     *
     * @return the value of userinfos.nickname
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfos.nickname
     *
     * @param nickname the value for userinfos.nickname
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfos.age
     *
     * @return the value of userinfos.age
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfos.age
     *
     * @param age the value for userinfos.age
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfos.email
     *
     * @return the value of userinfos.email
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfos.email
     *
     * @param email the value for userinfos.email
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfos.gmt_create
     *
     * @return the value of userinfos.gmt_create
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfos.gmt_create
     *
     * @param gmtCreate the value for userinfos.gmt_create
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfos.gmt_update
     *
     * @return the value of userinfos.gmt_update
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfos.gmt_update
     *
     * @param gmtUpdate the value for userinfos.gmt_update
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfos.is_delete
     *
     * @return the value of userinfos.is_delete
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfos.is_delete
     *
     * @param isDelete the value for userinfos.is_delete
     *
     * @mbggenerated Sat Apr 11 22:34:22 CST 2020
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}