package com.example.springbootdemo.common.db.dao.quartz.qrtzwimpletriggers.mapper;

import com.example.springbootdemo.common.db.dao.quartz.qrtzwimpletriggers.model.QrtzSimpleTriggers;
import com.example.springbootdemo.common.db.dao.quartz.qrtzwimpletriggers.model.QrtzSimpleTriggersExample;
import com.example.springbootdemo.common.db.dao.quartz.qrtzwimpletriggers.model.QrtzSimpleTriggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzSimpleTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    int countByExample(QrtzSimpleTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    int deleteByExample(QrtzSimpleTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    int deleteByPrimaryKey(QrtzSimpleTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    int insert(QrtzSimpleTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    int insertSelective(QrtzSimpleTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    List<QrtzSimpleTriggers> selectByExample(QrtzSimpleTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    QrtzSimpleTriggers selectByPrimaryKey(QrtzSimpleTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") QrtzSimpleTriggers record, @Param("example") QrtzSimpleTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    int updateByExample(@Param("record") QrtzSimpleTriggers record, @Param("example") QrtzSimpleTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    int updateByPrimaryKeySelective(QrtzSimpleTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPLE_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    int updateByPrimaryKey(QrtzSimpleTriggers record);
}