package com.example.springbootdemo.common.db.dao.zkdata.model;

import java.util.Date;

public class ZkData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zk_data.id
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zk_data.job_id
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    private String jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zk_data.gmt_create
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zk_data.gmt_update
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    private Date gmtUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zk_data.root
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    private String root;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zk_data.path
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zk_data.data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    private byte[] data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zk_data.id
     *
     * @return the value of zk_data.id
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zk_data.id
     *
     * @param id the value for zk_data.id
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zk_data.job_id
     *
     * @return the value of zk_data.job_id
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zk_data.job_id
     *
     * @param jobId the value for zk_data.job_id
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zk_data.gmt_create
     *
     * @return the value of zk_data.gmt_create
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zk_data.gmt_create
     *
     * @param gmtCreate the value for zk_data.gmt_create
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zk_data.gmt_update
     *
     * @return the value of zk_data.gmt_update
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zk_data.gmt_update
     *
     * @param gmtUpdate the value for zk_data.gmt_update
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zk_data.root
     *
     * @return the value of zk_data.root
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public String getRoot() {
        return root;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zk_data.root
     *
     * @param root the value for zk_data.root
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public void setRoot(String root) {
        this.root = root == null ? null : root.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zk_data.path
     *
     * @return the value of zk_data.path
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zk_data.path
     *
     * @param path the value for zk_data.path
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zk_data.data
     *
     * @return the value of zk_data.data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zk_data.data
     *
     * @param data the value for zk_data.data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}