package org.example.db.dao.mytab.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.db.dao.mytab.model.MyTab;
import org.example.db.dao.mytab.model.MyTabExample;

public interface MyTabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_tab
     *
     * @mbggenerated Tue Sep 22 20:58:08 CST 2020
     */
    int countByExample(MyTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_tab
     *
     * @mbggenerated Tue Sep 22 20:58:08 CST 2020
     */
    int deleteByExample(MyTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_tab
     *
     * @mbggenerated Tue Sep 22 20:58:08 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_tab
     *
     * @mbggenerated Tue Sep 22 20:58:08 CST 2020
     */
    int insert(MyTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_tab
     *
     * @mbggenerated Tue Sep 22 20:58:08 CST 2020
     */
    int insertSelective(MyTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_tab
     *
     * @mbggenerated Tue Sep 22 20:58:08 CST 2020
     */
    List<MyTab> selectByExample(MyTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_tab
     *
     * @mbggenerated Tue Sep 22 20:58:08 CST 2020
     */
    MyTab selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_tab
     *
     * @mbggenerated Tue Sep 22 20:58:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") MyTab record, @Param("example") MyTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_tab
     *
     * @mbggenerated Tue Sep 22 20:58:08 CST 2020
     */
    int updateByExample(@Param("record") MyTab record, @Param("example") MyTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_tab
     *
     * @mbggenerated Tue Sep 22 20:58:08 CST 2020
     */
    int updateByPrimaryKeySelective(MyTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_tab
     *
     * @mbggenerated Tue Sep 22 20:58:08 CST 2020
     */
    int updateByPrimaryKey(MyTab record);
}