package com.example.springbootdemo.common.db.dao.odps.mapper;

import com.example.springbootdemo.common.db.dao.odps.model.Odps;
import com.example.springbootdemo.common.db.dao.odps.model.OdpsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OdpsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    int countByExample(OdpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    int deleteByExample(OdpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    int insert(Odps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    int insertSelective(Odps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    List<Odps> selectByExampleWithBLOBs(OdpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    List<Odps> selectByExample(OdpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    Odps selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") Odps record, @Param("example") OdpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Odps record, @Param("example") OdpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    int updateByExample(@Param("record") Odps record, @Param("example") OdpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    int updateByPrimaryKeySelective(Odps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Odps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table odps
     *
     * @mbggenerated Sun Mar 15 00:03:37 CST 2020
     */
    int updateByPrimaryKey(Odps record);
}