package com.example.springbootdemo.common.db.dao.zkdata.mapper;

import com.example.springbootdemo.common.db.dao.zkdata.model.ZkData;
import com.example.springbootdemo.common.db.dao.zkdata.model.ZkDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZkDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    int countByExample(ZkDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    int deleteByExample(ZkDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    int insert(ZkData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    int insertSelective(ZkData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    List<ZkData> selectByExampleWithBLOBs(ZkDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    List<ZkData> selectByExample(ZkDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    ZkData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    int updateByExampleSelective(@Param("record") ZkData record, @Param("example") ZkDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") ZkData record, @Param("example") ZkDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    int updateByExample(@Param("record") ZkData record, @Param("example") ZkDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    int updateByPrimaryKeySelective(ZkData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(ZkData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zk_data
     *
     * @mbggenerated Wed Jan 27 22:15:02 CST 2021
     */
    int updateByPrimaryKey(ZkData record);
}