package com.example.springbootdemo.common.db.dao.quartz.qrtzpausedtriggersgrps.mapper;

import com.example.springbootdemo.common.db.dao.quartz.qrtzpausedtriggersgrps.model.QrtzPausedTriggersGrpsExample;
import com.example.springbootdemo.common.db.dao.quartz.qrtzpausedtriggersgrps.model.QrtzPausedTriggersGrpsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzPausedTriggersGrpsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    int countByExample(QrtzPausedTriggersGrpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    int deleteByExample(QrtzPausedTriggersGrpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    int deleteByPrimaryKey(QrtzPausedTriggersGrpsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    int insert(QrtzPausedTriggersGrpsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    int insertSelective(QrtzPausedTriggersGrpsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    List<QrtzPausedTriggersGrpsKey> selectByExample(QrtzPausedTriggersGrpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") QrtzPausedTriggersGrpsKey record, @Param("example") QrtzPausedTriggersGrpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    int updateByExample(@Param("record") QrtzPausedTriggersGrpsKey record, @Param("example") QrtzPausedTriggersGrpsExample example);
}