apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdemojar
  labels:
    app: springbootdemojar
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: springbootdemojar
  template:
    metadata:
      labels:
        app: springbootdemojar
    spec:
      containers:
        - name: springbootdemojar
          image: com.example.springboot-demo:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 30
          imagePullPolicy: IfNotPresent
      # Comment the following tolerations if Dashboard must not be deployed on master
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule

---
apiVersion: v1
kind: Service
metadata:
  name: springbootdemojar
  namespace: default
  labels:
    app: springbootdemojar
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: springbootdemojar
  type: NodePort
