apiVersion: v1
kind: Service
metadata:
  name: springboot-client
  namespace: default
  labels:
    app: springboot-client
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30091 #service对外开放端口
  selector:
    app: springboot-client
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: springboot-client #名称
  labels:
    app: springboot-client #标注
spec:
  replicas: 1 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: springboot-client
  template:
    metadata:
      labels:
        app: springboot-client
    spec:
      containers: #docker容器的配置
        - name: springboot-client
          image: com.example.nacos1:latest # pull镜像的地址 ip:prot/dir/images:tag
          imagePullPolicy: IfNotPresent #pull镜像时机，
          ports:
            - containerPort: 8080 #容器对外开放端口
