version: '2'
services:
   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
      volumes:
         - esdata1:/usr/share/elasticsearch/data
      networks:
         - elknet
      ports:
         - "9200:9200"
         - "9300:9300"
      environment:
         - cluster.name=es-cluster
         - "xpack.security.enabled=false"
         - bootstrap.memory_lock=true
         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
         memlock:
            soft: -1
            hard: -1
         nofile:
            soft: 65536
            hard: 65536
      mem_limit: 1g
      cap_add:
         - IPC_LOCK
   elasticsearch2:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
      volumes:
         - esdata2:/usr/share/elasticsearch/data
      networks:
         - elknet
      ports:
         - "9201:9200"
         - "9301:9300"
      environment:
         - cluster.name=es-cluster
         - "discovery.zen.ping.unicast.hosts=elasticsearch"
         - "xpack.security.enabled=false"
         - bootstrap.memory_lock=true
         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
         memlock:
            soft: -1
            hard: -1
         nofile:
            soft: 65536
            hard: 65536
      mem_limit: 1g
      cap_add:
         - IPC_LOCK
   kibana:
      image: docker.elastic.co/kibana/kibana:5.3.0
      networks:
         - elknet
      ports:
         - "9400:5601"
      environment:
         SERVER_NAME: localhost
         ELASTICSEARCH_URL: http://elasticsearch2:9200
         XPACK_SECURITY_ENABLED: "false"
      depends_on:
         - "elasticsearch"
   dockbeat:
      image: ingensi/dockbeat
      networks:
         - elknet
      volumes: 
         - /var/run/docker.sock:/var/run/docker.sock
      links: 
         - elasticsearch
networks: 
   elknet:
      external: true
volumes:
   esdata1:
   esdata2: