package com.example.springbootdemo.common.db.dao.quartz.qrtzpausedtriggersgrps.model;

public class QrtzPausedTriggersGrpsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    private String triggerGroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME
     *
     * @return the value of QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME
     *
     * @param schedName the value for QRTZ_PAUSED_TRIGGER_GRPS.SCHED_NAME
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
     *
     * @return the value of QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
     *
     * @param triggerGroup the value for QRTZ_PAUSED_TRIGGER_GRPS.TRIGGER_GROUP
     *
     * @mbggenerated Thu Oct 08 21:38:23 CST 2020
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup == null ? null : triggerGroup.trim();
    }
}