package com.example.springbootdemo.common.db.dao.quartz.qrtzjobdetails.mapper;

import com.example.springbootdemo.common.db.dao.quartz.qrtzjobdetails.model.QrtzJobDetails;
import com.example.springbootdemo.common.db.dao.quartz.qrtzjobdetails.model.QrtzJobDetailsExample;
import com.example.springbootdemo.common.db.dao.quartz.qrtzjobdetails.model.QrtzJobDetailsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzJobDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    int countByExample(QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    int deleteByExample(QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    int deleteByPrimaryKey(QrtzJobDetailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    int insert(QrtzJobDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    int insertSelective(QrtzJobDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    List<QrtzJobDetails> selectByExampleWithBLOBs(QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    List<QrtzJobDetails> selectByExample(QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    QrtzJobDetails selectByPrimaryKey(QrtzJobDetailsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    int updateByExampleSelective(@Param("record") QrtzJobDetails record, @Param("example") QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") QrtzJobDetails record, @Param("example") QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    int updateByExample(@Param("record") QrtzJobDetails record, @Param("example") QrtzJobDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    int updateByPrimaryKeySelective(QrtzJobDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(QrtzJobDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbggenerated Thu Oct 08 21:43:19 CST 2020
     */
    int updateByPrimaryKey(QrtzJobDetails record);
}