package com.example.springbootdemo.common.db.dao.executionlog.mapper;

import com.example.springbootdemo.common.db.dao.executionlog.model.ExecutionLog;
import com.example.springbootdemo.common.db.dao.executionlog.model.ExecutionLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExecutionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    int countByExample(ExecutionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    int deleteByExample(ExecutionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    int insert(ExecutionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    int insertSelective(ExecutionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    List<ExecutionLog> selectByExampleWithBLOBs(ExecutionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    List<ExecutionLog> selectByExample(ExecutionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    ExecutionLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") ExecutionLog record, @Param("example") ExecutionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") ExecutionLog record, @Param("example") ExecutionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    int updateByExample(@Param("record") ExecutionLog record, @Param("example") ExecutionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    int updateByPrimaryKeySelective(ExecutionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(ExecutionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_log
     *
     * @mbggenerated Fri Jan 22 23:05:14 CST 2021
     */
    int updateByPrimaryKey(ExecutionLog record);
}