package com.example.springbootdemo.common.db.dao.dbsavefront.model;

import java.util.Date;

public class DbSaveFront {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_save_front.id
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_save_front.key_string
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    private String keyString;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_save_front.value_string
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    private String valueString;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_save_front.gmt_create
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_save_front.gmt_update
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    private Date gmtUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_save_front.id
     *
     * @return the value of db_save_front.id
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_save_front.id
     *
     * @param id the value for db_save_front.id
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_save_front.key_string
     *
     * @return the value of db_save_front.key_string
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public String getKeyString() {
        return keyString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_save_front.key_string
     *
     * @param keyString the value for db_save_front.key_string
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public void setKeyString(String keyString) {
        this.keyString = keyString == null ? null : keyString.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_save_front.value_string
     *
     * @return the value of db_save_front.value_string
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public String getValueString() {
        return valueString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_save_front.value_string
     *
     * @param valueString the value for db_save_front.value_string
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public void setValueString(String valueString) {
        this.valueString = valueString == null ? null : valueString.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_save_front.gmt_create
     *
     * @return the value of db_save_front.gmt_create
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_save_front.gmt_create
     *
     * @param gmtCreate the value for db_save_front.gmt_create
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_save_front.gmt_update
     *
     * @return the value of db_save_front.gmt_update
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_save_front.gmt_update
     *
     * @param gmtUpdate the value for db_save_front.gmt_update
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }
}