package com.example.springbootdemo.common.db.dao.dbsavefront.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DbSaveFrontExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public DbSaveFrontExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andKeyStringIsNull() {
            addCriterion("key_string is null");
            return (Criteria) this;
        }

        public Criteria andKeyStringIsNotNull() {
            addCriterion("key_string is not null");
            return (Criteria) this;
        }

        public Criteria andKeyStringEqualTo(String value) {
            addCriterion("key_string =", value, "keyString");
            return (Criteria) this;
        }

        public Criteria andKeyStringNotEqualTo(String value) {
            addCriterion("key_string <>", value, "keyString");
            return (Criteria) this;
        }

        public Criteria andKeyStringGreaterThan(String value) {
            addCriterion("key_string >", value, "keyString");
            return (Criteria) this;
        }

        public Criteria andKeyStringGreaterThanOrEqualTo(String value) {
            addCriterion("key_string >=", value, "keyString");
            return (Criteria) this;
        }

        public Criteria andKeyStringLessThan(String value) {
            addCriterion("key_string <", value, "keyString");
            return (Criteria) this;
        }

        public Criteria andKeyStringLessThanOrEqualTo(String value) {
            addCriterion("key_string <=", value, "keyString");
            return (Criteria) this;
        }

        public Criteria andKeyStringLike(String value) {
            addCriterion("key_string like", value, "keyString");
            return (Criteria) this;
        }

        public Criteria andKeyStringNotLike(String value) {
            addCriterion("key_string not like", value, "keyString");
            return (Criteria) this;
        }

        public Criteria andKeyStringIn(List<String> values) {
            addCriterion("key_string in", values, "keyString");
            return (Criteria) this;
        }

        public Criteria andKeyStringNotIn(List<String> values) {
            addCriterion("key_string not in", values, "keyString");
            return (Criteria) this;
        }

        public Criteria andKeyStringBetween(String value1, String value2) {
            addCriterion("key_string between", value1, value2, "keyString");
            return (Criteria) this;
        }

        public Criteria andKeyStringNotBetween(String value1, String value2) {
            addCriterion("key_string not between", value1, value2, "keyString");
            return (Criteria) this;
        }

        public Criteria andValueStringIsNull() {
            addCriterion("value_string is null");
            return (Criteria) this;
        }

        public Criteria andValueStringIsNotNull() {
            addCriterion("value_string is not null");
            return (Criteria) this;
        }

        public Criteria andValueStringEqualTo(String value) {
            addCriterion("value_string =", value, "valueString");
            return (Criteria) this;
        }

        public Criteria andValueStringNotEqualTo(String value) {
            addCriterion("value_string <>", value, "valueString");
            return (Criteria) this;
        }

        public Criteria andValueStringGreaterThan(String value) {
            addCriterion("value_string >", value, "valueString");
            return (Criteria) this;
        }

        public Criteria andValueStringGreaterThanOrEqualTo(String value) {
            addCriterion("value_string >=", value, "valueString");
            return (Criteria) this;
        }

        public Criteria andValueStringLessThan(String value) {
            addCriterion("value_string <", value, "valueString");
            return (Criteria) this;
        }

        public Criteria andValueStringLessThanOrEqualTo(String value) {
            addCriterion("value_string <=", value, "valueString");
            return (Criteria) this;
        }

        public Criteria andValueStringLike(String value) {
            addCriterion("value_string like", value, "valueString");
            return (Criteria) this;
        }

        public Criteria andValueStringNotLike(String value) {
            addCriterion("value_string not like", value, "valueString");
            return (Criteria) this;
        }

        public Criteria andValueStringIn(List<String> values) {
            addCriterion("value_string in", values, "valueString");
            return (Criteria) this;
        }

        public Criteria andValueStringNotIn(List<String> values) {
            addCriterion("value_string not in", values, "valueString");
            return (Criteria) this;
        }

        public Criteria andValueStringBetween(String value1, String value2) {
            addCriterion("value_string between", value1, value2, "valueString");
            return (Criteria) this;
        }

        public Criteria andValueStringNotBetween(String value1, String value2) {
            addCriterion("value_string not between", value1, value2, "valueString");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtUpdateIsNull() {
            addCriterion("gmt_update is null");
            return (Criteria) this;
        }

        public Criteria andGmtUpdateIsNotNull() {
            addCriterion("gmt_update is not null");
            return (Criteria) this;
        }

        public Criteria andGmtUpdateEqualTo(Date value) {
            addCriterion("gmt_update =", value, "gmtUpdate");
            return (Criteria) this;
        }

        public Criteria andGmtUpdateNotEqualTo(Date value) {
            addCriterion("gmt_update <>", value, "gmtUpdate");
            return (Criteria) this;
        }

        public Criteria andGmtUpdateGreaterThan(Date value) {
            addCriterion("gmt_update >", value, "gmtUpdate");
            return (Criteria) this;
        }

        public Criteria andGmtUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_update >=", value, "gmtUpdate");
            return (Criteria) this;
        }

        public Criteria andGmtUpdateLessThan(Date value) {
            addCriterion("gmt_update <", value, "gmtUpdate");
            return (Criteria) this;
        }

        public Criteria andGmtUpdateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_update <=", value, "gmtUpdate");
            return (Criteria) this;
        }

        public Criteria andGmtUpdateIn(List<Date> values) {
            addCriterion("gmt_update in", values, "gmtUpdate");
            return (Criteria) this;
        }

        public Criteria andGmtUpdateNotIn(List<Date> values) {
            addCriterion("gmt_update not in", values, "gmtUpdate");
            return (Criteria) this;
        }

        public Criteria andGmtUpdateBetween(Date value1, Date value2) {
            addCriterion("gmt_update between", value1, value2, "gmtUpdate");
            return (Criteria) this;
        }

        public Criteria andGmtUpdateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_update not between", value1, value2, "gmtUpdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table db_save_front
     *
     * @mbggenerated do_not_delete_during_merge Sat Jan 16 20:15:28 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table db_save_front
     *
     * @mbggenerated Sat Jan 16 20:15:28 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}