package org.example.db.dao.uv.model;

public class Uv {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uv.ip
     *
     * @mbggenerated Tue Sep 22 20:59:04 CST 2020
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uv.ip
     *
     * @return the value of uv.ip
     *
     * @mbggenerated Tue Sep 22 20:59:04 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uv.ip
     *
     * @param ip the value for uv.ip
     *
     * @mbggenerated Tue Sep 22 20:59:04 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}