package org.example.db.dao.pv.model;

public class Pv {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pv.visit_count
     *
     * @mbggenerated Tue Sep 22 20:58:35 CST 2020
     */
    private Long visitCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pv.request_path
     *
     * @mbggenerated Tue Sep 22 20:58:35 CST 2020
     */
    private String requestPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pv.visit_count
     *
     * @return the value of pv.visit_count
     *
     * @mbggenerated Tue Sep 22 20:58:35 CST 2020
     */
    public Long getVisitCount() {
        return visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pv.visit_count
     *
     * @param visitCount the value for pv.visit_count
     *
     * @mbggenerated Tue Sep 22 20:58:35 CST 2020
     */
    public void setVisitCount(Long visitCount) {
        this.visitCount = visitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pv.request_path
     *
     * @return the value of pv.request_path
     *
     * @mbggenerated Tue Sep 22 20:58:35 CST 2020
     */
    public String getRequestPath() {
        return requestPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pv.request_path
     *
     * @param requestPath the value for pv.request_path
     *
     * @mbggenerated Tue Sep 22 20:58:35 CST 2020
     */
    public void setRequestPath(String requestPath) {
        this.requestPath = requestPath == null ? null : requestPath.trim();
    }
}