package org.example.db.dao.demotask.model;

public class DemoTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_task.id
     *
     * @mbggenerated Tue Sep 22 20:57:04 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_task.task_name
     *
     * @mbggenerated Tue Sep 22 20:57:04 CST 2020
     */
    private String taskName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_task.id
     *
     * @return the value of demo_task.id
     *
     * @mbggenerated Tue Sep 22 20:57:04 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_task.id
     *
     * @param id the value for demo_task.id
     *
     * @mbggenerated Tue Sep 22 20:57:04 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_task.task_name
     *
     * @return the value of demo_task.task_name
     *
     * @mbggenerated Tue Sep 22 20:57:04 CST 2020
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_task.task_name
     *
     * @param taskName the value for demo_task.task_name
     *
     * @mbggenerated Tue Sep 22 20:57:04 CST 2020
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }
}