package com.example.springbootdemo.common.db.dao.quartz.qrtzfiredtriggers.model;

public class QrtzFiredTriggersKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_FIRED_TRIGGERS.SCHED_NAME
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_FIRED_TRIGGERS.ENTRY_ID
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    private String entryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_FIRED_TRIGGERS.SCHED_NAME
     *
     * @return the value of QRTZ_FIRED_TRIGGERS.SCHED_NAME
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_FIRED_TRIGGERS.SCHED_NAME
     *
     * @param schedName the value for QRTZ_FIRED_TRIGGERS.SCHED_NAME
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_FIRED_TRIGGERS.ENTRY_ID
     *
     * @return the value of QRTZ_FIRED_TRIGGERS.ENTRY_ID
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    public String getEntryId() {
        return entryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_FIRED_TRIGGERS.ENTRY_ID
     *
     * @param entryId the value for QRTZ_FIRED_TRIGGERS.ENTRY_ID
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    public void setEntryId(String entryId) {
        this.entryId = entryId == null ? null : entryId.trim();
    }
}