package com.example.springbootdemo.common.db.dao.resource.model;

public class DmsResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated Fri Jan 03 22:27:07 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.user_id
     *
     * @mbggenerated Fri Jan 03 22:27:07 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.file_id
     *
     * @mbggenerated Fri Jan 03 22:27:07 CST 2020
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.file_name
     *
     * @mbggenerated Fri Jan 03 22:27:07 CST 2020
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated Fri Jan 03 22:27:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated Fri Jan 03 22:27:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.user_id
     *
     * @return the value of resource.user_id
     *
     * @mbggenerated Fri Jan 03 22:27:07 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.user_id
     *
     * @param userId the value for resource.user_id
     *
     * @mbggenerated Fri Jan 03 22:27:07 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.file_id
     *
     * @return the value of resource.file_id
     *
     * @mbggenerated Fri Jan 03 22:27:07 CST 2020
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.file_id
     *
     * @param fileId the value for resource.file_id
     *
     * @mbggenerated Fri Jan 03 22:27:07 CST 2020
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.file_name
     *
     * @return the value of resource.file_name
     *
     * @mbggenerated Fri Jan 03 22:27:07 CST 2020
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.file_name
     *
     * @param fileName the value for resource.file_name
     *
     * @mbggenerated Fri Jan 03 22:27:07 CST 2020
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }
}