package com.example.springbootdemo.common.db.dao.executionrecord.mapper;

import com.example.springbootdemo.common.db.dao.executionrecord.model.ExecutionRecord;
import com.example.springbootdemo.common.db.dao.executionrecord.model.ExecutionRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExecutionRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_record
     *
     * @mbggenerated Wed Sep 30 20:46:15 CST 2020
     */
    int countByExample(ExecutionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_record
     *
     * @mbggenerated Wed Sep 30 20:46:15 CST 2020
     */
    int deleteByExample(ExecutionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_record
     *
     * @mbggenerated Wed Sep 30 20:46:15 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_record
     *
     * @mbggenerated Wed Sep 30 20:46:15 CST 2020
     */
    int insert(ExecutionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_record
     *
     * @mbggenerated Wed Sep 30 20:46:15 CST 2020
     */
    int insertSelective(ExecutionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_record
     *
     * @mbggenerated Wed Sep 30 20:46:15 CST 2020
     */
    List<ExecutionRecord> selectByExample(ExecutionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_record
     *
     * @mbggenerated Wed Sep 30 20:46:15 CST 2020
     */
    ExecutionRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_record
     *
     * @mbggenerated Wed Sep 30 20:46:15 CST 2020
     */
    int updateByExampleSelective(@Param("record") ExecutionRecord record, @Param("example") ExecutionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_record
     *
     * @mbggenerated Wed Sep 30 20:46:15 CST 2020
     */
    int updateByExample(@Param("record") ExecutionRecord record, @Param("example") ExecutionRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_record
     *
     * @mbggenerated Wed Sep 30 20:46:15 CST 2020
     */
    int updateByPrimaryKeySelective(ExecutionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution_record
     *
     * @mbggenerated Wed Sep 30 20:46:15 CST 2020
     */
    int updateByPrimaryKey(ExecutionRecord record);
}