package org.example.db.dao.bizlock.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.example.db.dao.bizlock.model.BizLock;
import org.example.db.dao.bizlock.model.BizLockExample;

public interface BizLockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lock
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    int countByExample(BizLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lock
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    int deleteByExample(BizLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lock
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lock
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    int insert(BizLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lock
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    int insertSelective(BizLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lock
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    List<BizLock> selectByExample(BizLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lock
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    BizLock selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lock
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") BizLock record, @Param("example") BizLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lock
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    int updateByExample(@Param("record") BizLock record, @Param("example") BizLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lock
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    int updateByPrimaryKeySelective(BizLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_lock
     *
     * @mbggenerated Tue Sep 22 21:25:13 CST 2020
     */
    int updateByPrimaryKey(BizLock record);
}