package com.example.springbootdemo.common.db.dao.quartz.qrtzwimpletriggers.model;

public class QrtzSimpleTriggersKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_SIMPLE_TRIGGERS.SCHED_NAME
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    private String triggerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    private String triggerGroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_SIMPLE_TRIGGERS.SCHED_NAME
     *
     * @return the value of QRTZ_SIMPLE_TRIGGERS.SCHED_NAME
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_SIMPLE_TRIGGERS.SCHED_NAME
     *
     * @param schedName the value for QRTZ_SIMPLE_TRIGGERS.SCHED_NAME
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME
     *
     * @return the value of QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    public String getTriggerName() {
        return triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME
     *
     * @param triggerName the value for QRTZ_SIMPLE_TRIGGERS.TRIGGER_NAME
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName == null ? null : triggerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP
     *
     * @return the value of QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP
     *
     * @param triggerGroup the value for QRTZ_SIMPLE_TRIGGERS.TRIGGER_GROUP
     *
     * @mbggenerated Thu Oct 08 21:40:23 CST 2020
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup == null ? null : triggerGroup.trim();
    }
}