package com.example.springbootdemo.common.db.dao.quartz.qrtzsimproptriggers.mapper;

import com.example.springbootdemo.common.db.dao.quartz.qrtzsimproptriggers.model.QrtzSimpropTriggers;
import com.example.springbootdemo.common.db.dao.quartz.qrtzsimproptriggers.model.QrtzSimpropTriggersExample;
import com.example.springbootdemo.common.db.dao.quartz.qrtzsimproptriggers.model.QrtzSimpropTriggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzSimpropTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:23 CST 2020
     */
    int countByExample(QrtzSimpropTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:23 CST 2020
     */
    int deleteByExample(QrtzSimpropTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:23 CST 2020
     */
    int deleteByPrimaryKey(QrtzSimpropTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:23 CST 2020
     */
    int insert(QrtzSimpropTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:23 CST 2020
     */
    int insertSelective(QrtzSimpropTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:23 CST 2020
     */
    List<QrtzSimpropTriggers> selectByExample(QrtzSimpropTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:23 CST 2020
     */
    QrtzSimpropTriggers selectByPrimaryKey(QrtzSimpropTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:23 CST 2020
     */
    int updateByExampleSelective(@Param("record") QrtzSimpropTriggers record, @Param("example") QrtzSimpropTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:23 CST 2020
     */
    int updateByExample(@Param("record") QrtzSimpropTriggers record, @Param("example") QrtzSimpropTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:23 CST 2020
     */
    int updateByPrimaryKeySelective(QrtzSimpropTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_SIMPROP_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:41:23 CST 2020
     */
    int updateByPrimaryKey(QrtzSimpropTriggers record);
}