package com.example.springbootdemo.common.db.dao.executionrecord.model;

import java.util.Date;

public class ExecutionRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_record.id
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_record.gmt_create
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_record.gmt_update
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    private Date gmtUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_record.user_number
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    private String userNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_record.user_name
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_record.type
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_record.experiment_type
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    private String experimentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_record.status
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution_record.is_deleted
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_record.id
     *
     * @return the value of execution_record.id
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_record.id
     *
     * @param id the value for execution_record.id
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_record.gmt_create
     *
     * @return the value of execution_record.gmt_create
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_record.gmt_create
     *
     * @param gmtCreate the value for execution_record.gmt_create
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_record.gmt_update
     *
     * @return the value of execution_record.gmt_update
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_record.gmt_update
     *
     * @param gmtUpdate the value for execution_record.gmt_update
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_record.user_number
     *
     * @return the value of execution_record.user_number
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public String getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_record.user_number
     *
     * @param userNumber the value for execution_record.user_number
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber == null ? null : userNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_record.user_name
     *
     * @return the value of execution_record.user_name
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_record.user_name
     *
     * @param userName the value for execution_record.user_name
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_record.type
     *
     * @return the value of execution_record.type
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_record.type
     *
     * @param type the value for execution_record.type
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_record.experiment_type
     *
     * @return the value of execution_record.experiment_type
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public String getExperimentType() {
        return experimentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_record.experiment_type
     *
     * @param experimentType the value for execution_record.experiment_type
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public void setExperimentType(String experimentType) {
        this.experimentType = experimentType == null ? null : experimentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_record.status
     *
     * @return the value of execution_record.status
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_record.status
     *
     * @param status the value for execution_record.status
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution_record.is_deleted
     *
     * @return the value of execution_record.is_deleted
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution_record.is_deleted
     *
     * @param isDeleted the value for execution_record.is_deleted
     *
     * @mbggenerated Wed Sep 30 20:57:28 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}