package com.example.springbootdemo.common.db.dao.quartz.qrtzlocks.mapper;

import com.example.springbootdemo.common.db.dao.quartz.qrtzlocks.model.QrtzLocksExample;
import com.example.springbootdemo.common.db.dao.quartz.qrtzlocks.model.QrtzLocksKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzLocksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_LOCKS
     *
     * @mbggenerated Thu Oct 08 21:39:46 CST 2020
     */
    int countByExample(QrtzLocksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_LOCKS
     *
     * @mbggenerated Thu Oct 08 21:39:46 CST 2020
     */
    int deleteByExample(QrtzLocksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_LOCKS
     *
     * @mbggenerated Thu Oct 08 21:39:46 CST 2020
     */
    int deleteByPrimaryKey(QrtzLocksKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_LOCKS
     *
     * @mbggenerated Thu Oct 08 21:39:46 CST 2020
     */
    int insert(QrtzLocksKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_LOCKS
     *
     * @mbggenerated Thu Oct 08 21:39:46 CST 2020
     */
    int insertSelective(QrtzLocksKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_LOCKS
     *
     * @mbggenerated Thu Oct 08 21:39:46 CST 2020
     */
    List<QrtzLocksKey> selectByExample(QrtzLocksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_LOCKS
     *
     * @mbggenerated Thu Oct 08 21:39:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") QrtzLocksKey record, @Param("example") QrtzLocksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_LOCKS
     *
     * @mbggenerated Thu Oct 08 21:39:46 CST 2020
     */
    int updateByExample(@Param("record") QrtzLocksKey record, @Param("example") QrtzLocksExample example);
}