package com.example.springbootdemo.common.db.dao.resource.mapper;

import com.example.springbootdemo.common.db.dao.resource.model.DmsResource;
import com.example.springbootdemo.common.db.dao.resource.model.DmsResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DmsResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Feb 23 23:49:18 CST 2020
     */
    int countByExample(DmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Feb 23 23:49:18 CST 2020
     */
    int deleteByExample(DmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Feb 23 23:49:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Feb 23 23:49:18 CST 2020
     */
    int insert(DmsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Feb 23 23:49:18 CST 2020
     */
    int insertSelective(DmsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Feb 23 23:49:18 CST 2020
     */
    List<DmsResource> selectByExample(DmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Feb 23 23:49:18 CST 2020
     */
    DmsResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Feb 23 23:49:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") DmsResource record, @Param("example") DmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Feb 23 23:49:18 CST 2020
     */
    int updateByExample(@Param("record") DmsResource record, @Param("example") DmsResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Feb 23 23:49:18 CST 2020
     */
    int updateByPrimaryKeySelective(DmsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource
     *
     * @mbggenerated Sun Feb 23 23:49:18 CST 2020
     */
    int updateByPrimaryKey(DmsResource record);
}