package com.example.springbootdemo.common.db.dao.quartz.qrtzblobtriggers.model;

public class QrtzBlobTriggers extends QrtzBlobTriggersKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column QRTZ_BLOB_TRIGGERS.BLOB_DATA
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    private byte[] blobData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column QRTZ_BLOB_TRIGGERS.BLOB_DATA
     *
     * @return the value of QRTZ_BLOB_TRIGGERS.BLOB_DATA
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    public byte[] getBlobData() {
        return blobData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column QRTZ_BLOB_TRIGGERS.BLOB_DATA
     *
     * @param blobData the value for QRTZ_BLOB_TRIGGERS.BLOB_DATA
     *
     * @mbggenerated Thu Oct 08 21:42:26 CST 2020
     */
    public void setBlobData(byte[] blobData) {
        this.blobData = blobData;
    }
}