spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: zhf123..
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 5
        min-idle: 0
    timeout: 5000ms
logging:
  path: ./logs