package com.example.springbootdemo.common.db.dao.quartz.qrtzfiredtriggers.mapper;

import com.example.springbootdemo.common.db.dao.quartz.qrtzfiredtriggers.model.QrtzFiredTriggers;
import com.example.springbootdemo.common.db.dao.quartz.qrtzfiredtriggers.model.QrtzFiredTriggersExample;
import com.example.springbootdemo.common.db.dao.quartz.qrtzfiredtriggers.model.QrtzFiredTriggersKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzFiredTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_FIRED_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    int countByExample(QrtzFiredTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_FIRED_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    int deleteByExample(QrtzFiredTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_FIRED_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    int deleteByPrimaryKey(QrtzFiredTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_FIRED_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    int insert(QrtzFiredTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_FIRED_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    int insertSelective(QrtzFiredTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_FIRED_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    List<QrtzFiredTriggers> selectByExample(QrtzFiredTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_FIRED_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    QrtzFiredTriggers selectByPrimaryKey(QrtzFiredTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_FIRED_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    int updateByExampleSelective(@Param("record") QrtzFiredTriggers record, @Param("example") QrtzFiredTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_FIRED_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    int updateByExample(@Param("record") QrtzFiredTriggers record, @Param("example") QrtzFiredTriggersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_FIRED_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    int updateByPrimaryKeySelective(QrtzFiredTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_FIRED_TRIGGERS
     *
     * @mbggenerated Thu Oct 08 21:37:24 CST 2020
     */
    int updateByPrimaryKey(QrtzFiredTriggers record);
}