apiVersion: v1
kind: Service
metadata:
  name: springbootdemo
  namespace: default
  labels:
    app: springbootdemo
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30090 #service对外开放端口
  selector:
    app: springbootdemo
---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: springbootdemo #名称
  labels:
    app: springbootdemo #标注
spec:
  replicas: 3 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: springbootdemo
  template:
    metadata:
      labels:
        app: springbootdemo
    spec:
      containers: #docker容器的配置
        - name: springbootdemo
          image: com.example.springboot-demo:latest # pull镜像的地址 ip:prot/dir/images:tag
          imagePullPolicy: IfNotPresent #pull镜像时机，
          ports:
            - containerPort: 8080 #容器对外开放端口
